# Generated by Django 5.2.17 on 2026-09-14 21:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                (
                    "asset_type",
                    models.CharField(choices=[("STOCK", "Stock"), ("ETF", "ETF")], max_length=16),
                ),
                ("exchange", models.CharField(max_length=64)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("symbol", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("asset_type__in", ("STOCK", "ETF"))),
                        name="asset_type_supported",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency", "USD")), name="asset_currency_usd"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("symbol", ""), _negated=True),
                        name="asset_symbol_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True), name="asset_name_nonblank"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("exchange", ""), _negated=True),
                        name="asset_exchange_nonblank",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetProviderSymbol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                ("provider_symbol", models.CharField(max_length=64)),
                ("is_primary", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_symbols",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "ordering": ("provider", "provider_symbol", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_symbol"), name="asset_provider_identity_uniq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider", ""), _negated=True),
                        name="asset_provider_nonblank",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider_symbol", ""), _negated=True),
                        name="asset_provider_symbol_nonblank",
                    ),
                ],
            },
        ),
    ]
