"""Framework-independent deterministic Phase 6 backtesting foundation."""

from portfolio_engine.backtesting.context import BacktestStrategy, StrategyContext
from portfolio_engine.backtesting.contracts import (
    BACKTEST_METHOD_VERSION,
    BacktestAssumptions,
    BacktestCostObservation,
    BacktestDataProvenance,
    BacktestDecision,
    BacktestEquityObservation,
    BacktestError,
    BacktestErrorCode,
    BacktestExecutionEvent,
    BacktestInitialPosition,
    BacktestProvenance,
    BacktestResult,
    BacktestReturnObservation,
    BacktestWarning,
    BacktestWarningCode,
    OrderIntent,
    OrderSide,
    PortfolioLedgerState,
    PortfolioPositionSnapshot,
    PortfolioState,
    PositionQuantity,
    SimulatedFill,
)
from portfolio_engine.backtesting.engine import run_backtest

__all__ = [
    "BACKTEST_METHOD_VERSION",
    "BacktestAssumptions",
    "BacktestCostObservation",
    "BacktestDataProvenance",
    "BacktestDecision",
    "BacktestEquityObservation",
    "BacktestError",
    "BacktestErrorCode",
    "BacktestExecutionEvent",
    "BacktestInitialPosition",
    "BacktestProvenance",
    "BacktestResult",
    "BacktestReturnObservation",
    "BacktestStrategy",
    "BacktestWarning",
    "BacktestWarningCode",
    "OrderIntent",
    "OrderSide",
    "PortfolioLedgerState",
    "PortfolioPositionSnapshot",
    "PortfolioState",
    "PositionQuantity",
    "SimulatedFill",
    "StrategyContext",
    "run_backtest",
]
