# Generated by Django 5.2.17 on 2026-09-16 19:24

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("portfolios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OptimizationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("EQUAL_WEIGHT", "Equal weight"),
                            ("MINIMUM_VARIANCE", "Minimum variance"),
                            ("MAXIMUM_SHARPE", "Maximum Sharpe"),
                            ("EFFICIENT_FRONTIER", "Efficient frontier"),
                        ],
                        max_length=32,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("provider", models.CharField(max_length=32)),
                ("price_field", models.CharField(default="adjusted_close", max_length=32)),
                ("annualization_factor", models.PositiveSmallIntegerField(default=252)),
                (
                    "risk_free_rate_annual",
                    models.DecimalField(decimal_places=12, default=Decimal("0"), max_digits=18),
                ),
                ("included_asset_ids", models.JSONField(default=list)),
                ("parameters", models.JSONField(default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("warnings", models.JSONField(default=list)),
                ("engine_version", models.CharField(default="0.1.0.dev0", max_length=64)),
                ("method_version", models.CharField(default="1.0", max_length=32)),
                ("data_retrieved_at", models.DateTimeField(blank=True, null=True)),
                ("data_fingerprint", models.CharField(blank=True, max_length=64)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("failure_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "benchmark_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benchmark_optimization_runs",
                        to="assets.asset",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization_runs",
                        to="portfolios.portfolio",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
    ]
