# Generated by Django 5.2.17 on 2026-09-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("optimization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optimizationrun",
            name="warnings",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
