# Generated by Django 5.2.17 on 2026-09-14 21:54

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_currency", models.CharField(default="USD", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "benchmark_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benchmark_portfolios",
                        to="assets.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("DIVIDEND", "Dividend"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("source_sequence", models.PositiveBigIntegerField(default=0)),
                (
                    "quantity",
                    models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "fees",
                    models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=20),
                ),
                (
                    "cash_amount",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_transactions",
                        to="assets.asset",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "source_sequence", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="portfolio",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_currency", "USD")), name="portfolio_base_currency_usd"
            ),
        ),
        migrations.AddConstraint(
            model_name="portfolio",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True), name="portfolio_name_nonblank"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("fees__gte", 0)), name="transaction_fees_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("asset__isnull", True),
                        ("cash_amount__gt", 0),
                        ("cash_amount__isnull", False),
                        ("price__isnull", True),
                        ("quantity__isnull", True),
                        ("transaction_type__in", ("DEPOSIT", "WITHDRAWAL")),
                    ),
                    models.Q(
                        ("asset__isnull", False),
                        ("cash_amount__isnull", True),
                        ("price__gt", 0),
                        ("price__isnull", False),
                        ("quantity__gt", 0),
                        ("quantity__isnull", False),
                        ("transaction_type__in", ("BUY", "SELL")),
                    ),
                    models.Q(
                        ("asset__isnull", False),
                        ("cash_amount__gt", 0),
                        ("cash_amount__isnull", False),
                        ("transaction_type", "DIVIDEND"),
                        models.Q(("quantity__isnull", True), ("quantity__gt", 0), _connector="OR"),
                        models.Q(("price__isnull", True), ("price__gt", 0), _connector="OR"),
                    ),
                    _connector="OR",
                ),
                name="transaction_fields_match_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "occurred_at", "source_sequence"),
                name="transaction_portfolio_time_sequence_uniq",
            ),
        ),
    ]
