# Generated by Django 5.2.17 on 2026-09-17 13:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("optimization", "0002_alter_optimizationrun_warnings"),
        ("portfolios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_allocations",
                        to="portfolios.portfolio",
                    ),
                ),
                (
                    "source_optimization_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_allocations",
                        to="optimization.optimizationrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="RebalanceSimulation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("as_of", models.DateTimeField()),
                ("provider", models.CharField(max_length=32)),
                ("price_field", models.CharField(default="close", max_length=32)),
                ("valuation_retrieved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "drift_threshold",
                    models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True),
                ),
                ("schedule", models.CharField(blank=True, max_length=16)),
                ("previous_rebalance_date", models.DateField(blank=True, null=True)),
                ("result", models.JSONField()),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rebalance_simulations",
                        to="portfolios.portfolio",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rebalance_simulations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rebalance_simulations",
                        to="rebalancing.targetallocation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="TargetAllocationWeight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_cash", models.BooleanField(default=False)),
                ("weight", models.DecimalField(decimal_places=12, max_digits=18)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_allocation_weights",
                        to="assets.asset",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="rebalancing.targetallocation",
                    ),
                ),
            ],
            options={
                "ordering": ("is_cash", "asset_id", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="targetallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="target_allocation_name_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetallocationweight",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gte", 0), ("weight__lte", 1)),
                name="target_weight_unit_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetallocationweight",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("asset__isnull", True), ("is_cash", True)),
                    models.Q(("asset__isnull", False), ("is_cash", False)),
                    _connector="OR",
                ),
                name="target_weight_cash_identity_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetallocationweight",
            constraint=models.UniqueConstraint(
                fields=("target", "asset"), name="target_allocation_asset_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="targetallocationweight",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cash", True)),
                fields=("target",),
                name="target_allocation_single_cash",
            ),
        ),
    ]
